---
- name: Ensure pre-reqs installed
  package:
    name: "{{ elastalert_pkgs }}"
  become: true

- name: Establish system group
  group:
    name: "{{ elastalert_group }}"
  become: true

- name: Establish system user
  user:
    name: "{{ elastalert_user }}"
    group: "{{ elastalert_group }}"
    shell: /bin/false
  become: true

- name: Ensure etc directory in place
  file:
    state: directory
    path: "{{ elastalert_etc_root }}"
    owner: root
    group: "{{ elastalert_group }}"
    mode: "0750"
  become: true
